export type CaseStat = {
  label: string;
  value: string;
};

export type CaseSection = {
  heading: string;
  body: string[];
  bullets?: string[];
};

export type CaseMoment = {
  title: string;
  body: string;
};

export type CaseStudy = {
  slug: string;
  name: string;
  url: string;
  tagline: string;
  summary: string;
  sector: string;
  location: string;
  engagementLabel: string;
  stats: CaseStat[];
  situation: string[];
  problem: string[];
  sections: CaseSection[];
  hardParts: CaseMoment[];
  timeline: CaseMoment[];
  outcome: string[];
  scopeNote: string;
  stack: string[];
  logo: string;
  order: number;
  accent: string;
};

export const companyProof = {
  productsShipped: "15+",
  continents: "6",
  mission:
    "We ship AI-native product engineering for startups and teams that are stuck. Old waterfall habits and slow agency practices don't scale — we pick up the pace and get the work into market.",
  whoWeHelp:
    "Startups and product teams struggling to move. We embed engineers — in squads or solo — and turn stalled roadmaps into live product.",
} as const;

export const caseStudies: CaseStudy[] = [
  {
    slug: "floor-nexus",
    name: "Floor Nexus",
    url: "https://floornexus.com/",
    tagline: "Vertical SaaS for specialty flooring contractors",
    summary:
      "Floor Nexus had a product that looked roughly seventy percent finished and behaved like it was nowhere near it. Fluid Web took over technology ownership, stripped out the majority of what was there, and rebuilt the platform across five surfaces with a team that grew to sixteen engineers.",
    sector: "Vertical SaaS · Construction",
    location: "Florida, USA",
    engagementLabel: "Technology ownership · team of 12+",
    stats: [
      { label: "Processed to date", value: "$500K" },
      { label: "Engineers today", value: "12" },
      { label: "Product surfaces", value: "5" },
      { label: "Release cadence", value: "Weekly+" },
    ],
    situation: [
      "Floor Nexus arrived with a codebase that had been largely AI-generated by a previous team whose seniority had been overstated to the founder. By the time we were brought in, most of that team had already been let go — two people were retained, a strong backend developer and an app lead.",
      "The product was not a blank page and it was not a working platform either. Enough existed to demo, which is the most expensive state a product can be in, because it looks finished to everyone except the people trying to extend it.",
    ],
    problem: [
      "The gap between what the product appeared to be and what it could actually support was the whole problem. Roughly seventy percent of the surface area existed in some form, but a large share of it could not be built on — it had to be stripped out and rebuilt before anything new could land safely.",
      "That created a commercial constraint that shaped everything after. Floor Nexus had paying contractors using the platform, so the rebuild had to happen underneath live customers, with no freeze on new features while it did.",
    ],
    sections: [
      {
        heading: "Rebuilding roughly sixty percent of the product under live traffic",
        body: [
          "We assessed what could be kept and what could not, and the honest answer was that around sixty percent of the existing product needed to be stripped out and rebuilt. That is not a recommendation anyone enjoys delivering, but pretending otherwise would have meant stacking new features on foundations that were already the reason delivery had stalled.",
          "The rebuild ran in phases behind live traffic over roughly five months. New implementations went in alongside old ones, usage shifted across gradually, and the old paths came out last. At no point did the roadmap freeze — the company kept shipping customer-visible work the entire time the structural replacement was happening underneath it.",
        ],
        bullets: [
          "Assessment of what could be salvaged before anything was promised",
          "Phased replacement behind live traffic rather than a cutover",
          "Feature delivery continued throughout the rebuild",
          "Legacy paths removed only once replacements had proven themselves",
        ],
      },
      {
        heading: "Building one team out of two",
        body: [
          "Staffing was its own problem. We interviewed the founder's former team, brought two of them back on their merits alongside the two already retained, and let the rest go. That gave us four people who carried real institutional knowledge of the product and its customers.",
          "On top of that we brought in four to six Fluid Web engineers to start. When the company secured investment, we scaled the Fluid Web side by another eight, taking the combined team to roughly sixteen. Today twelve engineers are active on the platform, and expansion is still underway.",
        ],
        bullets: [
          "Client team members re-interviewed and retained on technical merit",
          "Four to six Fluid Web engineers embedded at the start",
          "Scaled by another eight engineers once funding closed",
          "Single team, shared standards — not a vendor working alongside staff",
        ],
      },
      {
        heading: "Five product surfaces built in parallel",
        body: [
          "Floor Nexus is not one application. Contractors run jobs from an installer platform and a mobile app, homeowners track their work through a customer portal, manufacturers and distributors operate through a vendor platform with its own storefront and point-of-sale, and the company runs all of it through an admin layer.",
          "Each of those surfaces has different users, different permissions and different failure modes, but they resolve against one product model. Building them in parallel rather than sequentially is the only way they stay coherent — mobile that ships a year behind web is not a surface, it is a liability.",
        ],
        bullets: [
          "Installer platform for contractors running jobs end to end",
          "Mobile applications for field teams who are not at a desk",
          "Homeowner portal so customers can follow their own project",
          "Vendor platform with white-label storefront and point-of-sale",
          "Admin and analytics layer for running the business",
        ],
      },
      {
        heading: "Rebuilding billing from per-user to per-business, mid-flight",
        body: [
          "Billing was one of the clearest symptoms of the original build. Everything was modelled at the user level — there were no business-level plans at all — which is the wrong shape for a product sold to contracting companies where one business has a crew, an office team and an owner who all need access. Charging per individual and having no concept of a company account meant the commercial model the business actually wanted was not expressible in the software.",
          "Fixing that meant reworking the entitlement model so plans attach to a business, with seats and permissions resolving underneath it. That is not a billing change so much as a tenancy change, because who pays and who has access have to agree with each other at every level.",
          "On top of the model rework, we migrated the entire payment setup from an old Stripe account onto a new one, and from the legacy integration onto Stripe's newer API. Moving billing between accounts on a product that is actively collecting money is about as unforgiving as this work gets — active subscriptions, payment methods and in-flight transactions all have to land intact, and customers cannot notice.",
        ],
        bullets: [
          "Entitlements re-modelled from individual users to business-level plans",
          "Seats and permissions resolved under a company account",
          "Full migration from a legacy Stripe account to a new one",
          "Upgraded onto Stripe's newer API rather than patching the old integration",
          "Executed against live subscriptions without disrupting collection",
        ],
      },
      {
        heading: "A catalog and vendor network underneath it all",
        body: [
          "The platform supports roughly forty-five manufacturers and around eight thousand products that installers can quote and order against. Keeping a catalog that size coherent — pricing tiers, availability, warranty rules, vendor-specific terms — is quietly one of the harder parts of the system.",
          "Five manufacturers now run their CRM and point-of-sale directly on the vendor platform, with more onboarding in December. That turns Floor Nexus from a contractor tool into a marketplace with both sides operating on it.",
        ],
      },
      {
        heading: "Shipping weekly from the first week",
        body: [
          "Weekly shipping started the day we took over, and in practice it is often several releases a week. That was deliberate: on a rescue, restoring visible delivery early is what rebuilds confidence internally, and it forces the deployment path to become reliable before anyone depends on it for something large.",
          "It also meant the founder could stay on customers, partnerships and fundraising instead of managing engineering, which is where the real leverage was.",
        ],
      },
    ],
    hardParts: [
      {
        title: "Judging what to keep",
        body: "AI-generated code is not uniformly bad, and treating it as such would have thrown away working functionality. The difficult work was separating what was merely unfamiliar from what was genuinely unsafe to build on — file by file, not by blanket verdict.",
      },
      {
        title: "Rebuilding without a freeze",
        body: "Paying contractors were running jobs on the platform throughout. Every structural change had to be reversible and had to coexist with the thing it was replacing, which is slower than a rewrite and the only responsible option.",
      },
      {
        title: "Scaling a team mid-rebuild",
        body: "Going from four to sixteen people while restructuring the codebase risks each new engineer multiplying the inconsistency. Conventions and written decisions had to be established before the second wave arrived, not after.",
      },
      {
        title: "Migrating live billing between Stripe accounts",
        body: "Moving active subscriptions and payment methods onto a new Stripe account and a newer API version, while the platform was collecting money, offers no margin for error. A failed charge here is not a bug report — it is a customer losing access to the software they run their jobs on.",
      },
      {
        title: "Catalog integrity at scale",
        body: "Forty-five manufacturers and roughly eight thousand products means vendor-specific pricing, warranty and availability rules that cannot be special-cased indefinitely without the system collapsing under its own exceptions.",
      },
    ],
    timeline: [
      {
        title: "Takeover and assessment",
        body: "Technology ownership transferred, former team members interviewed and selectively re-hired, and an honest read taken on what could be salvaged.",
      },
      {
        title: "Strip and rebuild",
        body: "Roughly five months of phased replacement behind live traffic, with weekly shipping in place from the first week.",
      },
      {
        title: "Funded expansion",
        body: "Investment closed and the Fluid Web team scaled by another eight engineers, taking the combined team to around sixteen.",
      },
      {
        title: "Marketplace build-out",
        body: "Vendor platform, storefront and point-of-sale brought live, with manufacturers onboarding onto their own CRM and POS.",
      },
    ],
    outcome: [
      "Floor Nexus runs on a platform that is substantially larger than the one we inherited — we describe it internally as going from a product that was seventy percent built to something several times its original scope, across five surfaces that did not meaningfully exist before.",
      "Billing now runs on business-level plans on a modern Stripe integration, migrated from a legacy account and API without interrupting collection — which turned a commercial model the company could not previously express into one it sells on today.",
      "The platform has processed approximately $500,000 in transactions to date. Five manufacturers operate their CRM and point-of-sale on the vendor platform, with more onboarding in December, against a catalog of roughly forty-five manufacturers and eight thousand products.",
      "Twelve engineers ship weekly and frequently more often. Technology ownership sits with Fluid Web, which is why the founder's time goes to customers and growth rather than engineering triage.",
    ],
    scopeNote:
      "Fluid Web owns technology and engineering delivery. Product direction, client relationships and go-to-market decisions sit with the founder — we build against them rather than setting them.",
    stack: [
      "Multi-tenant web platform",
      "iOS and Android applications",
      "Stripe Connect payments",
      "Business-level plans and entitlements",
      "QuickBooks Online sync",
      "Twilio messaging and voice",
      "In-product AI assistance",
    ],
    logo: "/logos/floor-nexus.png",
    order: 1,
    accent: "#5B8DEF",
  },
  {
    slug: "treply",
    name: "Treply",
    url: "https://treply.so/",
    tagline: "SMS / MMS engagement for nonprofits & agencies",
    summary:
      "Treply was a two-year engagement where Fluid Web's founder led engineering and, in practice, ran the company's delivery function. The platform peaked at two million messages a month across enterprise tenants and white-label agency partners.",
    sector: "SaaS · Messaging",
    location: "Illinois, USA",
    engagementLabel: "Engineering leadership · 2 years",
    stats: [
      { label: "Peak volume", value: "2M msgs / mo" },
      { label: "Sustained average", value: "700K / mo" },
      { label: "Enterprise tenants", value: "6–7" },
      { label: "Engagement", value: "2 years" },
    ],
    situation: [
      "Treply set out to give nonprofits and the agencies serving them a real messaging platform rather than a thin wrapper over a provider API. Customers were coming off tools like Attentive, Crisp and Bird — products built for retail marketing that fit the nonprofit motion badly.",
      "Our founder joined to lead engineering and ended up leading considerably more than that. Over two years the role covered technical leadership, product design, client communication and, when the chief executive was away, running payroll for the local team.",
    ],
    problem: [
      "The platform had to serve two different customers at once. Enterprise nonprofits needed their own tenant with real volume behind it, while agencies needed to run branded workspaces for the organisations they served — which is a white-label problem, not a permissions problem.",
      "Underneath that sat the harder constraint: messaging at scale is governed by carriers, not by your roadmap. Consent, registration, opt-out handling and throughput all had to be correct before volume could grow, because getting them wrong means filtering rather than an error message.",
    ],
    sections: [
      {
        heading: "Multi-tenant from the foundation, not retrofitted",
        body: [
          "Treply was built as a multi-tenant platform from the start, with enterprise tenants and agency workspaces modelled as first-class concepts rather than as an access-control afterthought. That decision is the reason white-label support was possible at all later on.",
          "At its peak the platform ran six to seven enterprise tenants alongside two white-label agency partners, each operating under their own brand while running on a single deployment.",
        ],
        bullets: [
          "Tenant isolation designed before feature work began",
          "Agency workspaces managing their own downstream organisations",
          "Branding and identity stored as tenant data, never as a fork",
          "One codebase and one deploy serving every brand on the platform",
        ],
      },
      {
        heading: "Volume that carriers would actually accept",
        body: [
          "The platform peaked at roughly two million SMS and MMS messages a month and sustained an average near seven hundred thousand. Reaching those numbers is less about throughput engineering than about compliance being correct from the beginning.",
          "Consent capture, opt-out enforcement and carrier registration were modelled in the product rather than handled by process. A send that would damage sender reputation had to be difficult to perform by accident, because at that volume a reputation problem is not recoverable in a sprint.",
        ],
        bullets: [
          "Consent and opt-out enforced in the data model, not in support process",
          "Carrier registration tracked as product state",
          "Throughput control and retry logic that never double-sent",
          "Delivery health surfaced to the operators running campaigns",
        ],
      },
      {
        heading: "Leading the team and the delivery function",
        body: [
          "The team reached ten people, and our founder led it across scrum, stories, technical direction and design. In practice the remit extended past engineering — client communication and, at times, paying the local team's salaries.",
          "That is unusual to say in a case study, but it is the honest description of the engagement and it is why the pattern repeats. Several of the engineers led on Treply are, two years later, working under Fluid Web again.",
        ],
      },
      {
        heading: "Shipping the marketing site alongside the product",
        body: [
          "The marketing site was part of the same engagement rather than handed to a separate vendor. For a product selling into nonprofits and agencies, the site and the onboarding flow are one continuous experience, and splitting them across two teams creates a seam that nobody owns.",
        ],
      },
    ],
    hardParts: [
      {
        title: "Two customer shapes on one platform",
        body: "Enterprise tenants and white-label agencies want incompatible things. Agencies need control over branding and their own customer hierarchy; enterprises need isolation and their own scale. Serving both without forking the product is a tenancy design problem you only get one chance at.",
      },
      {
        title: "Deliverability as a growth ceiling",
        body: "At two million messages a month, carrier filtering is an existential risk rather than a support ticket. Compliance had to be built into the send path itself so that the safe action was also the default one.",
      },
      {
        title: "Leadership load beyond engineering",
        body: "Running design, client communication and payroll alongside technical leadership is not a structure we would recommend, and it taught us where the boundaries of an engagement should sit. It is part of why Fluid Web engagements now include delivery management explicitly.",
      },
    ],
    timeline: [
      {
        title: "Greenfield build",
        body: "Platform built from an empty repository — tenancy, messaging pipeline, campaign tooling and the marketing site.",
      },
      {
        title: "Enterprise and agency onboarding",
        body: "Six to seven enterprise tenants brought on alongside two white-label agency partners running their own branded workspaces.",
      },
      {
        title: "Volume scale",
        body: "Sustained averages near 700,000 messages a month, peaking around two million, with compliance and deliverability holding at that scale.",
      },
      {
        title: "Handover",
        body: "Our founder moved on after roughly two years. Work added to the platform after that point is not ours to claim.",
      },
    ],
    outcome: [
      "Treply went from an empty repository to a production messaging platform running six to seven enterprise tenants and two white-label agency partners on a single deployment.",
      "Volume peaked at approximately two million SMS and MMS messages a month with a sustained average around seven hundred thousand, replacing tools like Attentive, Crisp and Bird for customers whose needs those products were never designed around.",
      "The engagement ran two years with a team of up to ten. Several of those engineers work under Fluid Web today, which is the clearest signal we can offer about how the team was run.",
    ],
    scopeNote:
      "Our involvement covers the platform, agency and admin consoles, and the marketing site during a roughly two-year period. Features added after our founder's departure — including later faith-specific donation functionality — are not our work and we make no claim to them.",
    stack: [
      "Multi-tenant SaaS platform",
      "SMS and MMS at production volume",
      "White-label agency workspaces",
      "Campaign and delivery tooling",
      "Marketing site",
    ],
    logo: "/logos/treply.svg",
    order: 2,
    accent: "#6EE7B7",
  },
  {
    slug: "ppv-my",
    name: "PPV.MY",
    url: "https://ppv.my/",
    tagline: "Combat-sports pay-per-view for Malaysia",
    summary:
      "Malaysian fight promoters had no reliable way to sell pay-per-view. Fluid Web built the entire platform — storefront, live streaming, local payments and organiser admin — and launched in December. Five public events have run since, drawing roughly 50,000 unique views.",
    sector: "Media · Live streaming",
    location: "Malaysia",
    engagementLabel: "Full product build · ownership stake",
    stats: [
      { label: "Public events", value: "5" },
      { label: "Unique views", value: "~50K" },
      { label: "Broadcast length", value: "3–6 hrs" },
      { label: "Live since", value: "December 2025" },
    ],
    situation: [
      "Independent combat-sports promotions in Malaysia were stuck between two bad options. International OTT platforms ignored local payment rails, which is fatal in a market where most buyers are not paying by international card. Do-it-yourself streaming leaked revenue and looked unprofessional on the night that mattered most.",
      "The result was that promoters either did not sell pay-per-view at all or reassembled a fragile setup for every single card. Fluid Web built the platform to remove that problem, and holds an ownership stake in the business alongside a partner who competes in the sport.",
    ],
    problem: [
      "Pay-per-view has a failure mode most software does not: everything converges on one unforgiving window. Thousands of people buy within the same hour, the stream must hold for a three to six hour broadcast, and there is no opportunity to apologise and retry next sprint.",
      "On top of that, checkout had to work for Malaysian buyers first. A platform that only accepts international cards has already lost the majority of its audience before the stream is even tested.",
    ],
    sections: [
      {
        heading: "Built for the buying spike, not average load",
        body: [
          "Event-based pay-per-view has a traffic profile unlike subscription products. Demand is close to zero for weeks, then a large share of all purchases lands in the hour before the first fight, followed by simultaneous playback starts.",
          "The platform is built around that shape. Checkout and entitlement issuance are designed for the spike, and playback access is verified without becoming the bottleneck at exactly the moment everyone presses play at once.",
        ],
        bullets: [
          "Per-event purchase and entitlement rather than subscription access",
          "Checkout designed for concentrated pre-event demand",
          "Access verification that holds when playback starts simultaneously",
          "Replay windows so buyers who miss the live broadcast still get value",
        ],
      },
      {
        heading: "Local payments first, international second",
        body: [
          "Billplz handles Malaysian payment rails, with Stripe covering international cards for the diaspora audience. That ordering matters — building international-first and adding local rails later would have meant launching into the wrong market with the right technology.",
          "Both paths resolve to the same entitlement model, so a buyer's access does not depend on how they paid.",
        ],
        bullets: [
          "Billplz for Malaysian payment methods as the primary rail",
          "Stripe for international cards alongside it",
          "One entitlement model regardless of payment path",
          "Purchase and access state visible to organisers in real time",
        ],
      },
      {
        heading: "Streaming that holds for a six-hour card",
        body: [
          "Live delivery runs on Mux with HLS playback and replay windows afterwards. Fight cards run three to six hours, which is a long time for everything in the chain to behave — a platform that is fine for a thirty-minute test is not necessarily fine at hour four.",
          "Replay matters commercially as much as technically. A meaningful share of buyers in a market spanning several timezones watch after the fact, so replay access is part of the product rather than a courtesy.",
        ],
      },
      {
        heading: "Organiser admin so promoters do not need engineers",
        body: [
          "The point of the platform is that a promotion can run a card without standing up engineering for it. Organisers create events, configure pricing and access windows, manage streams, and watch sales and viewership as the night unfolds.",
          "Fluid Web built the marketing site and support flows in the same engagement, because for a consumer purchase made under time pressure, the site and the checkout are one experience.",
        ],
      },
    ],
    hardParts: [
      {
        title: "One shot per event",
        body: "There is no staged rollout for a live fight night. The platform either works during the two hours that matter or the promotion loses both the revenue and the audience's trust.",
      },
      {
        title: "Payment rails that actually convert locally",
        body: "Malaysian buyers needed Malaysian payment methods. Getting that right meant treating international cards as the secondary path, which is the opposite of how most platforms are built.",
      },
      {
        title: "Long-duration broadcast stability",
        body: "Three to six hour streams expose problems that short tests never surface. Stability across the full card, including replay availability immediately afterwards, was a distinct engineering concern.",
      },
    ],
    timeline: [
      {
        title: "Full product build",
        body: "Storefront, streaming pipeline, dual payment rails, organiser admin and marketing site built as a single engagement.",
      },
      {
        title: "December launch",
        body: "Platform went live and began selling real fight cards rather than pilots.",
      },
      {
        title: "Five public events",
        body: "Cards run across boxing, Muay Thai and mixed martial arts, drawing roughly 50,000 unique views in total.",
      },
      {
        title: "Continued development",
        body: "Two further events scheduled for October and a mobile application in progress.",
      },
    ],
    outcome: [
      "PPV.MY launched in December and has run five public events, drawing approximately 50,000 unique views across cards lasting three to six hours each.",
      "Promoters now run events from a single admin rather than reassembling a streaming and payment setup for every card, with Malaysian payment rails as the primary checkout path and international cards alongside.",
      "Two further events are scheduled for October and a mobile application is in development. Fluid Web owns the technology and holds a stake in the business.",
    ],
    scopeNote:
      "Fluid Web built and owns the entire technology stack, including the marketing site. Event promotion, matchmaking and commercial partnerships sit with our Malaysian partner.",
    stack: [
      "Mux live streaming and HLS playback",
      "Billplz for Malaysian payments",
      "Stripe for international cards",
      "React single-page application",
      "Organiser admin and analytics",
      "Mobile application in development",
    ],
    logo: "/logos/ppv-my.svg",
    order: 3,
    accent: "#F59E0B",
  },
  {
    slug: "clinicos",
    name: "clinicOS",
    url: "https://myclinicos.com.au/",
    tagline: "Staff operations for Australian GP practices",
    summary:
      "Australian general practices were running operations across spreadsheets, group chats and email. Fluid Web deployed an eight-person team to build clinicOS — rostering, internal communications, AI document intake and invoicing — now in use across seven practices with mobile apps live on both stores.",
    sector: "Healthcare SaaS",
    location: "Australia",
    engagementLabel: "Team of 8 · product delivery",
    stats: [
      { label: "Fluid Web team", value: "8" },
      { label: "Practices in access", value: "7" },
      { label: "Mobile", value: "iOS + Android" },
      { label: "Building since", value: "March" },
    ],
    situation: [
      "General practices run on a surprising amount of informal infrastructure. Rosters live in spreadsheets, announcements happen in group chats, correspondence arrives by email and invoicing sits in a separate system entirely — with staff acting as the integration layer between all of them.",
      "The operator behind clinicOS runs practices directly, so the product is built from the inside rather than from market research. Fluid Web deployed a team of eight in March to build it.",
    ],
    problem: [
      "Healthcare makes the obvious shortcut unavailable. Practices were losing hours every week to administrative glue, and the fastest fix — pasting patient correspondence into a general-purpose AI tool — is exactly the thing a medical practice cannot responsibly do.",
      "So the product had to deliver the time savings people wanted from AI while keeping data inside a controlled environment and keeping a human in front of anything that gets filed to a record.",
    ],
    sections: [
      {
        heading: "One practice directory underneath every module",
        body: [
          "Rostering, communications, document intake and invoicing all resolve against a single practice directory with role-based access. That sounds obvious and it is the thing most practice software gets wrong — separate modules with separate user lists is how staff end up maintaining the same information four times.",
          "Because roles are defined once, a practice manager, a nurse and a receptionist see appropriately different products without anyone maintaining three configurations.",
        ],
        bullets: [
          "Single staff directory shared across every module",
          "Role-based access so practices stay audit-ready",
          "Multi-tenant isolation between practices at the data layer",
          "Consistent permissions across web and mobile clients",
        ],
      },
      {
        heading: "AI intake with a human in front of the record",
        body: [
          "Document intake is where the time savings are. Incoming correspondence gets read, classified and structured automatically, which removes the manual sorting that consumes administrative hours every week.",
          "What it does not do is file anything unreviewed. Extracted output goes to a person before it reaches a record, with the source document alongside it so verification takes seconds. In healthcare the review step is not a limitation of the technology — it is the design.",
        ],
        bullets: [
          "Automated classification and extraction of incoming correspondence",
          "Human review before anything is filed to a record",
          "Source document retained alongside extracted values for verification",
          "Data kept within a controlled environment rather than pasted into consumer tools",
        ],
      },
      {
        heading: "Mobile because practice staff are not at a desk",
        body: [
          "Clinical and reception staff spend their day moving. A rostering and communications product that only exists on a desktop gets used at the start and end of a shift and ignored in between, which is precisely when it would be useful.",
          "Mobile applications are live on both iOS and Android, built in parallel with the web product against the same permission model rather than trailing it.",
        ],
      },
      {
        heading: "Australian data posture from the start",
        body: [
          "Hosting and data residency were settled early rather than discovered during a customer's security review. For Australian healthcare, that is a prerequisite to the first serious conversation, not a compliance task to schedule later.",
        ],
      },
    ],
    hardParts: [
      {
        title: "AI in a setting that cannot tolerate silent errors",
        body: "A wrong extraction that reaches a patient record is a materially different category of failure from a wrong extraction in most products. Confidence thresholds and review queues had to be designed before the feature shipped, not tuned after complaints.",
      },
      {
        title: "Modules that would rather be separate products",
        body: "Rostering, messaging, intake and invoicing have little in common functionally. Keeping them coherent under one directory and one permission model takes deliberate restraint against letting each grow its own concepts.",
      },
      {
        title: "Web and mobile parity from day one",
        body: "Shipping both surfaces simultaneously with a team of eight means the API contract has to be right early, because divergence between clients is far more expensive to unwind than to prevent.",
      },
    ],
    timeline: [
      {
        title: "Team deployed",
        body: "Eight Fluid Web engineers embedded from around March, covering web, mobile, AI and the marketing site.",
      },
      {
        title: "Core modules",
        body: "Rostering, internal communications, document intake and invoicing built against a shared practice directory.",
      },
      {
        title: "Mobile launch",
        body: "Applications shipped to both the iOS App Store and Google Play.",
      },
      {
        title: "Early access",
        body: "Seven practices now using the platform, with development continuing.",
      },
    ],
    outcome: [
      "clinicOS is in early access with seven Australian practices, replacing an assortment of spreadsheets, group chats and separate invoicing with a single staff workspace.",
      "Mobile applications are live on both iOS and Android, built in parallel with the web product rather than behind it.",
      "AI document intake is in production with human review before anything reaches a record — the time savings practices wanted from AI, without the data posture they could not accept.",
    ],
    scopeNote:
      "Fluid Web delivers engineering across web, mobile, AI and the marketing site. Clinical workflow decisions come from the practice operators behind the product. We do not name the client here given the healthcare context.",
    stack: [
      "Multi-tenant web platform",
      "iOS and Android applications",
      "AI document intake with human review",
      "Role-based access control",
      "Australian-region hosting",
    ],
    logo: "/logos/clinicos.svg",
    order: 4,
    accent: "#38BDF8",
  },
  {
    slug: "smartfaktura",
    name: "SmartFaktura",
    url: "https://app.smartfaktura.tech",
    tagline: "Cloud invoicing for Rwandan SMEs",
    summary:
      "A Norwegian founder needed invoicing software built for Rwandan small businesses. One Fluid Web engineer took it from nothing to production in six weeks, and has shipped thirteen milestones since — currently a full Rwandan tax engine.",
    sector: "Fintech · SME invoicing",
    location: "Norway · Rwanda",
    engagementLabel: "Solo senior embed",
    stats: [
      { label: "To production", value: "6 weeks" },
      { label: "Milestones shipped", value: "13" },
      { label: "Team size", value: "1 engineer" },
      { label: "Building since", value: "January" },
    ],
    situation: [
      "Rwandan small businesses were invoicing on Excel and paper. European accounting suites were available but wrong for the market — too heavy, priced for a different economy, and built around tax rules that do not apply.",
      "The founder, based in Norway and building for Rwanda, needed working software rather than a hiring plan. Fluid Web put one senior engineer on it in January.",
    ],
    problem: [
      "The immediate constraint was time. Standing up a local engineering team, or running a conventional agency engagement with a discovery phase attached, would have consumed months before an invoice could be issued.",
      "The deeper constraint was that localisation was the entire product. Rwandan VAT, TIN handling and local currency are not settings on top of a generic invoicing tool — they are the reason the tool exists at all.",
    ],
    sections: [
      {
        heading: "Production in six weeks, with one engineer",
        body: [
          "The first version reached production six weeks after the engagement started: invoice creation, sending, tracking, PDF generation and payment states. Not a prototype — the software a business could actually run on.",
          "One engineer was the right shape for this. Coordination overhead across a team would have cost more than the throughput it added, and a single person holding the whole system could move through decisions without negotiating interfaces.",
        ],
        bullets: [
          "Invoice creation, delivery, tracking and PDF generation",
          "Customer, product and expense management",
          "Payment state tracking through the invoice lifecycle",
          "Deployed to production rather than staged as a demo",
        ],
      },
      {
        heading: "Milestones instead of a fixed scope",
        body: [
          "After launch the engagement continued as a sequence of milestones, thirteen shipped so far. That structure suits a founder discovering the market in real time far better than a fixed statement of work agreed before the first customer existed.",
          "Each milestone is scoped against what the product actually needs next rather than what someone predicted it would need in January.",
        ],
        bullets: [
          "Multi-organisation support so accountants can run several companies",
          "Subscription billing across Free, Pro and Business tiers",
          "Expense tracking and VAT reporting",
          "Ongoing milestone delivery against live market feedback",
        ],
      },
      {
        heading: "Building a Rwandan tax engine",
        body: [
          "The current milestone is a full Rwandan tax engine. This is the part that cannot be borrowed from a European product — local VAT treatment, TIN handling and the reporting obligations that come with them have to be modelled correctly rather than approximated.",
          "It is also the strongest defensive position the product has. Generic invoicing tools can enter the market at any time; a correct local tax engine is what they cannot trivially copy.",
        ],
      },
    ],
    hardParts: [
      {
        title: "Jurisdiction-specific tax logic",
        body: "Tax engines are unforgiving. There is no partial credit for an invoice that is nearly compliant, and the rules cannot be inferred from how another country does it.",
      },
      {
        title: "Solo delivery without concentration risk",
        body: "One engineer building an entire financial product means documentation and conventional structure are not optional extras. The codebase has to be ordinary enough for someone else to pick up.",
      },
      {
        title: "Scope discipline at speed",
        body: "Six weeks to production only works if scope is cut honestly. Everything that was not required to send a real invoice waited for a later milestone.",
      },
    ],
    timeline: [
      {
        title: "January start",
        body: "One senior engineer embedded, scope cut to what was needed to issue a real invoice.",
      },
      {
        title: "Production at six weeks",
        body: "Core invoicing, customers, products and payment states live in production.",
      },
      {
        title: "Platform expansion",
        body: "Multi-organisation support, subscription billing across three tiers, expenses and VAT reporting.",
      },
      {
        title: "Milestone thirteen",
        body: "A full Rwandan tax engine, currently in build.",
      },
    ],
    outcome: [
      "SmartFaktura went from nothing to production in six weeks with a single engineer, and the founder launched without first building an engineering payroll.",
      "Thirteen milestones have shipped since, taking the product from core invoicing through multi-organisation support and subscription billing to a full Rwandan tax engine now in development.",
      "The engagement continues on a milestone basis, scoped against what the market asks for rather than what was predicted before launch.",
    ],
    scopeNote:
      "Fluid Web built and continues to build the application at app.smartfaktura.tech. The pre-existing marketing site was not part of our scope.",
    stack: [
      "Full-stack web application",
      "Stripe subscription billing",
      "Multi-organisation architecture",
      "Rwandan VAT and TIN handling",
      "PDF generation and delivery",
    ],
    logo: "/logos/smartfaktura.png",
    order: 5,
    accent: "#A3E635",
  },
  {
    slug: "voxtell",
    name: "Voxtell AI",
    url: "https://www.voxtell.ai/",
    tagline: "White-label AI voice for telecom partners",
    summary:
      "Voxtell sells AI voice agents through telecom resellers, which means the product has to carry someone else's brand and survive real phone calls. Fluid Web migrated the voice pipeline between providers in three weeks, replaced the authentication layer, and built the white-label theming that lets partners sell it as their own.",
    sector: "AI · Telecom",
    location: "Florida, USA",
    engagementLabel: "AI voice engineering · white-label",
    stats: [
      { label: "Pipeline migration", value: "3 weeks" },
      { label: "Platform migrations", value: "2" },
      { label: "Telephony", value: "Twilio" },
      { label: "Model", value: "White-label" },
    ],
    situation: [
      "Voxtell's go-to-market runs through telecom partners and resellers rather than direct to small businesses. That changes the engineering requirements substantially: the product has to be deeply rebrandable, and it has to be reliable enough that a partner will put their own name on it.",
      "Fluid Web was brought in as full-stack engineering on the AI voice side, working on the calling pipeline, telephony, transcription, messaging and the white-label layer.",
    ],
    problem: [
      "The platform was built on Retell, which was working, but was behind on the AI capabilities the product roadmap depended on. Staying put meant the roadmap was capped by someone else's release schedule.",
      "Separately, the authentication layer was causing friction that a library choice should not cause — a small problem that quietly taxes every feature built on top of it.",
    ],
    sections: [
      {
        heading: "Migrating the voice pipeline in three weeks",
        body: [
          "We moved the production voice pipeline from Retell to Vapi over roughly three weeks. The honest framing matters here: call reliability was comparable on both, so this was not a rescue from a failing provider. It was a capability decision — Vapi had the AI features the roadmap needed and Retell did not have them at the time, and the commercial terms were favourable.",
          "Vapi sitting on top of Twilio meant the telephony integration stayed coherent through the move rather than requiring a parallel rebuild of the call path.",
        ],
        bullets: [
          "Production voice pipeline migrated in approximately three weeks",
          "Driven by AI capability access, not by reliability problems",
          "Telephony continuity maintained through Twilio underneath",
          "Live calling, transcription and post-call messaging preserved across the move",
        ],
      },
      {
        heading: "Replacing the authentication layer",
        body: [
          "We also migrated authentication from NextAuth to Better Auth. This is the kind of work that never appears on a roadmap and pays for itself repeatedly — the previous library was not serving the product well, and every feature built on top of a difficult auth layer inherits that difficulty.",
          "Replacing it was a contained piece of work with a compounding return across everything built afterwards.",
        ],
      },
      {
        heading: "White-label deep enough for partners to sell",
        body: [
          "Reseller businesses fail on shallow white-labelling. If a partner's customers can tell they are looking at someone else's product, the partner will not sell it — and a logo swap is not sufficient to hide that.",
          "The theming layer goes considerably deeper, so partners present a product that reads as theirs, with multi-tenant patterns underneath built for reseller scale rather than for a handful of accounts.",
        ],
        bullets: [
          "Theming deep enough that partners present the product as their own",
          "Multi-tenant structure designed for reseller distribution",
          "Partner-facing surfaces alongside the end-customer product",
          "Branding as tenant configuration rather than per-partner builds",
        ],
      },
      {
        heading: "Voice, transcription and messaging on one thread",
        body: [
          "An AI receptionist that only handles the call is half a product. Calls produce transcripts, transcripts produce follow-ups, and follow-ups happen over messaging — all of which needs to resolve to the same customer rather than three disconnected systems.",
          "We built the calling, transcription and post-call messaging paths to share that context.",
        ],
      },
    ],
    hardParts: [
      {
        title: "Migrating a live voice product",
        body: "Voice is the least forgiving surface to migrate. Calls are synchronous and real people are on them, so there is no window where a degraded state goes unnoticed.",
      },
      {
        title: "Choosing to move for capability, not crisis",
        body: "Migrating a working system on the basis of future capability is a harder argument to make than fixing something broken, and it requires being honest that reliability was not the reason.",
      },
      {
        title: "White-label depth versus maintainability",
        body: "Every additional layer of brand customisation is another dimension of configuration to keep working. Going deep without letting partner-specific behaviour fragment the codebase is the real constraint.",
      },
    ],
    timeline: [
      {
        title: "Embedded as full-stack engineering",
        body: "Joined on the AI voice side covering the calling pipeline, telephony, transcription and messaging.",
      },
      {
        title: "Provider migration",
        body: "Production pipeline moved from Retell to Vapi in roughly three weeks, retaining Twilio telephony underneath.",
      },
      {
        title: "Authentication replacement",
        body: "NextAuth replaced with Better Auth, removing friction that was taxing every feature above it.",
      },
      {
        title: "White-label depth",
        body: "Theming and multi-tenant patterns extended for partner distribution.",
      },
    ],
    outcome: [
      "Voxtell's voice pipeline moved to a provider whose AI capabilities matched the roadmap, in approximately three weeks, without losing live calling, transcription or messaging.",
      "The authentication layer was replaced with one that stopped taxing feature work, and the white-label theming went deep enough for partners to sell the product under their own brand.",
      "Partners can offer AI receptionists without building voice infrastructure, on a multi-tenant foundation designed for reseller scale.",
    ],
    scopeNote:
      "Our work covers the AI voice pipeline, telephony, transcription, messaging, authentication and white-label theming, with partial involvement in the partner portal. We did not build the NetSapiens integration or the marketing site, and we do not have visibility into Voxtell's call volume or partner numbers.",
    stack: [
      "Vapi voice agent platform",
      "Twilio telephony",
      "Real-time transcription",
      "Better Auth",
      "Multi-tenant white-label theming",
    ],
    logo: "/logos/voxtell.png",
    order: 6,
    accent: "#FB7185",
  },
  {
    slug: "otteri",
    name: "Otteri AI",
    url: "https://otteri.ai/",
    tagline: "All-in-one AI productivity workspace",
    summary:
      "Otteri set out to replace a stack of single-purpose AI subscriptions with one workspace. Fluid Web led the greenfield build and took it from an empty repository to a launched product with paid tiers and a browser extension in roughly six months.",
    sector: "AI productivity",
    location: "Illinois, USA",
    engagementLabel: "Led greenfield build · 6 months",
    stats: [
      { label: "Zero to launch", value: "6 months" },
      { label: "Build", value: "From scratch" },
      { label: "Surfaces", value: "Web + extension" },
      { label: "Models", value: "Multi-provider" },
    ],
    situation: [
      "Operators were paying for several AI tools at once — one for writing, another for research, another for images — with no shared credits, no shared context and a separate subscription for each.",
      "Otteri was the answer to that: one workspace, one subscription, multiple models. Our founder led the build with the same team behind Treply, both products belonging to the same owner.",
    ],
    problem: [
      "Aggregation products live or die on breadth arriving fast enough to be credible. A workspace that only does two of the five things a user came for is worse than the fragmented stack it replaces, because now they are paying for it as well.",
      "That meant shipping a wide surface area quickly, without the product becoming a loose collection of wrappers around other people's APIs.",
    ],
    sections: [
      {
        heading: "One workspace across multiple model providers",
        body: [
          "Chat across multiple models, research, content generation, image and media creation, and document intelligence over PDFs, web pages and video — all under one login, one credit pool and one subscription.",
          "The provider layer had to be abstracted from the start, because a product whose entire premise is multi-model cannot have vendor specifics leaking into feature code.",
        ],
        bullets: [
          "Multi-model chat under a single account and credit pool",
          "Research and long-form content generation flows",
          "Image and creative media generation",
          "Document intelligence across PDFs, websites and video",
          "Prompt library and browser extension for in-workflow use",
        ],
      },
      {
        heading: "Breadth without becoming a pile of wrappers",
        body: [
          "The failure mode for this category is a product where each capability is a thin, disconnected shell around a different API. Users feel it immediately — nothing shares context, and the whole is worth less than the parts.",
          "Shared account, credit and context models underneath every surface are what made it one product rather than several bolted together.",
        ],
      },
      {
        heading: "Launched with real subscriptions, not a waitlist",
        body: [
          "Otteri launched with paid Pro and Teams tiers and a Chrome extension, roughly six months from an empty repository. Multi-seat team plans were part of the architecture rather than a later addition, since the team plan is where this category's revenue concentrates.",
        ],
      },
    ],
    hardParts: [
      {
        title: "Shipping wide and fast simultaneously",
        body: "Aggregation products need breadth to be credible at launch, which pulls directly against the usual advice to ship narrow. Getting there in six months meant shared foundations doing a lot of work across surfaces.",
      },
      {
        title: "Provider abstraction as a founding constraint",
        body: "With several providers behind one interface from day one, the abstraction had to be right early. Retrofitting it across an existing multi-model product would have been a rewrite.",
      },
      {
        title: "Credits across unlike operations",
        body: "A chat message, a research run and an image generation cost wildly different amounts. Presenting that as one comprehensible credit pool is a product design problem as much as an engineering one.",
      },
    ],
    timeline: [
      {
        title: "Greenfield start",
        body: "Empty repository, shared team with Treply, our founder leading the build.",
      },
      {
        title: "Core surfaces",
        body: "Multi-model chat, research, content and media generation on shared account and credit foundations.",
      },
      {
        title: "Document intelligence and extension",
        body: "PDF, web and video understanding, plus a Chrome extension for use inside existing workflows.",
      },
      {
        title: "Launch",
        body: "Shipped with paid Pro and Teams tiers roughly six months from the start.",
      },
    ],
    outcome: [
      "Otteri went from an empty repository to a launched product with paid Pro and Teams tiers and a Chrome extension in approximately six months, under Fluid Web leadership.",
      "The workspace covered multi-model chat, research, content and media generation, and document intelligence across PDFs, websites and video — a breadth most aggregation products take considerably longer to reach.",
      "Our involvement ended when our founder moved on. The product continued for a few months afterwards and is no longer actively operating, so we make no claims about its commercial performance.",
    ],
    scopeNote:
      "Fluid Web led the engineering build through to launch. Our involvement ended with our founder's departure, and we have no visibility into usage or revenue figures — we present this as a build-and-launch engagement, not an ongoing product success story.",
    stack: [
      "Multi-provider AI abstraction layer",
      "Shared credit and entitlement system",
      "Document and media intelligence pipelines",
      "Chrome extension",
      "Multi-seat team plans",
    ],
    logo: "/logos/otteri.png",
    order: 7,
    accent: "#2DD4BF",
  },
];

export const allCaseStudiesSorted = [...caseStudies].sort(
  (a, b) => a.order - b.order,
);

export const featuredCaseStudies = allCaseStudiesSorted;

export function getCaseStudy(slug: string) {
  return caseStudies.find((c) => c.slug === slug);
}

export const geographyHighlights = [
  "Illinois, USA",
  "California, USA",
  "Florida, USA",
  "France",
  "Australia",
  "Malaysia",
  "Norway · Rwanda",
  "Chile",
] as const;

export type MapProject = {
  name: string;
  slug?: string;
};

export type MapPin = {
  id: string;
  label: string;
  detail: string;
  lat: number;
  lng: number;
  accent: string;
  projects: MapProject[];
};

export const mapPins: MapPin[] = [
  {
    id: "illinois",
    label: "Illinois, USA",
    detail: "Nexobe portfolio",
    lat: 41.6986,
    lng: -88.0684,
    accent: "#6EE7B7",
    projects: [
      { name: "Treply", slug: "treply" },
      { name: "Otteri AI", slug: "otteri" },
      { name: "GoodOff" },
      { name: "Pikcel" },
      { name: "Snap.Photo" },
    ],
  },
  {
    id: "california",
    label: "California, USA",
    detail: "Rank.ai",
    lat: 37.7749,
    lng: -122.4194,
    accent: "#C084FC",
    projects: [{ name: "Rank.ai" }],
  },
  {
    id: "jacksonville",
    label: "Florida, USA",
    detail: "Floor Nexus",
    lat: 30.0819,
    lng: -81.5478,
    accent: "#5B8DEF",
    projects: [{ name: "Floor Nexus", slug: "floor-nexus" }],
  },
  {
    id: "orlando",
    label: "Florida, USA",
    detail: "Voxtell AI",
    lat: 28.5383,
    lng: -81.3792,
    accent: "#FB7185",
    projects: [{ name: "Voxtell AI", slug: "voxtell" }],
  },
  {
    id: "france",
    label: "France",
    detail: "Jarik · Dealwey",
    lat: 45.764,
    lng: 4.8357,
    accent: "#F472B6",
    projects: [{ name: "Jarik" }, { name: "Dealwey" }],
  },
  {
    id: "australia",
    label: "Australia",
    detail: "clinicOS · Practice Pro",
    lat: -25.2744,
    lng: 133.7751,
    accent: "#38BDF8",
    projects: [
      { name: "clinicOS", slug: "clinicos" },
      { name: "Practice Pro" },
    ],
  },
  {
    id: "malaysia",
    label: "Malaysia",
    detail: "PPV.MY",
    lat: 3.139,
    lng: 101.6869,
    accent: "#F59E0B",
    projects: [{ name: "PPV.MY", slug: "ppv-my" }],
  },
  {
    id: "norway",
    label: "Norway",
    detail: "SmartFaktura",
    lat: 59.9139,
    lng: 10.7522,
    accent: "#A3E635",
    projects: [{ name: "SmartFaktura", slug: "smartfaktura" }],
  },
  {
    id: "rwanda",
    label: "Rwanda",
    detail: "SmartFaktura",
    lat: -1.9441,
    lng: 30.0619,
    accent: "#A3E635",
    projects: [{ name: "SmartFaktura", slug: "smartfaktura" }],
  },
  {
    id: "chile",
    label: "Chile",
    detail: "Plenor",
    lat: -33.4489,
    lng: -70.6693,
    accent: "#FBBF24",
    projects: [{ name: "Plenor" }],
  },
  {
    id: "radar-usa",
    label: "United States",
    detail: "Radar",
    lat: 39.7392,
    lng: -104.9903,
    accent: "#94A3B8",
    projects: [{ name: "Radar" }],
  },
];
